CorvallisOR/Controllers/AuthController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using CorvallisOR.Models;

namespace CorvallisOR.Controllers
{
    public class AuthController : Controller
    {
        protected UserManager<Member> userManager = new UserManager<Member>(
                new UserStore<Member>(new ForumDb()));

        // GET: Auth
        public ActionResult Login(string returnUrl)
        {
            var model = new LoginVM
            {
                ReturnUrl = returnUrl
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult LogIn(LoginVM model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var user = userManager.Find(model.Username, model.Password);

            if (user != null)
            {
                var identity = userManager.CreateIdentity(
                    user, DefaultAuthenticationTypes.ApplicationCookie);

                GetAuthenticationManager().SignIn(identity);

                Session["user"] = user.Name;
                var manager = new UserManager<Member>(
                        new UserStore<Member>(new ForumDb()));
                if (manager.IsInRole(user.Id, "Admin") || manager.IsInRole(user.Id, "SuperAdmin"))
                {
                    Session["admin"] = true;
                }
                else
                {
                    Session["admin"] = false;
                }

                return Redirect(GetRedirectUrl(model.ReturnUrl));
            }

            // user authN failed
            ModelState.AddModelError("", "Invalid email or password");
            return View();
        }

        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(RegisterVM model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var user = new Member
            {
                UserName = model.Username,
                Name = model.Name,
            };

            var result = userManager.Create(user, model.Password);

            if (result.Succeeded)
            {
                SignIn(user);
                Session["user"] = user.Name;
                return RedirectToAction("index", "home");
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }

            return View();
        }

        private void SignIn(Member user)
        {
            var identity = userManager.CreateIdentity(user, DefaultAuthenticationTypes.ApplicationCookie);
            GetAuthenticationManager().SignIn(identity);
        }

        private string GetRedirectUrl(string returnUrl)
        {
            if (string.IsNullOrEmpty(returnUrl) || !Url.IsLocalUrl(returnUrl))
            {
                return Url.Action("index", "home");
            }

            return returnUrl;
        }

        private IAuthenticationManager GetAuthenticationManager()
        {
            var ctx = Request.GetOwinContext();
            return ctx.Authentication;
        }


        public ActionResult LogOut()
        {
            var ctx = Request.GetOwinContext();
            var authManager = ctx.Authentication;

            authManager.SignOut("ApplicationCookie");
            return RedirectToAction("index", "home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && userManager != null)
            {
                userManager.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CorvallisOR/Controllers/RolesController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CorvallisOR.Models;

namespace CorvallisOR.Controllers
{
    [Authorize(Roles = "Admin, SuperAdmin")]
    public class RolesController : Controller
    {
        private ForumDb context = new ForumDb();
        // GET: Roles
        public ActionResult Index()
        {
            var roles = context.Roles.ToList();
            return View(roles);
        }

        // GET: /Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Roles/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                context.Roles.Add(new Microsoft.AspNet.Identity.EntityFramework.IdentityRole()
                {
                    Name = collection["RoleName"]
                });
                context.SaveChanges();
                ViewBag.ResultMessage = "Role created successfully !";
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(string RoleName)
        {
            var thisRole = context.Roles.Where(r => r.Name.Equals(RoleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            context.Roles.Remove(thisRole);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        //
        // GET: /Roles/Edit/5
        public ActionResult Edit(string roleName)
        {
            var thisRole = context.Roles.Where(r => r.Name.Equals(roleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            return View(thisRole);
        }

        //
        // POST: /Roles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Microsoft.AspNet.Identity.EntityFramework.IdentityRole role)
        {
            try
            {
                context.Entry(role).State = System.Data.Entity.EntityState.Modified;
                context.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult ManageUserRoles()
        {
            // prepopulate roles for the view dropdown
            UserRoleVM userRole = new UserRoleVM
            {
                UserList = context.Users.OrderBy(u => u.Name).ToList().Select(u =>
                  new SelectListItem { Value = u.Id, Text = u.Name }).ToList(),
                RoleList = context.Roles.OrderBy(r => r.Name).ToList().Select(rr =>
                  new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList()
            };
            Session["userID"] = null;
            return View(userRole);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RoleAddToUser([Bind(Include = "Add")]UserRoleVM userRole)
        {
            if (Session["userID"] != null)
            {
                string userID = (string)Session["userID"];
                if (userRole.Add != null)
                {
                    var manager = new UserManager<Member>(
                    new UserStore<Member>(
                        new ForumDb()));
                    manager.AddToRole(userID, userRole.Add);
                }
                userRole = PopulateVM(userID);
                return View("ManageUserRoles", userRole);
            }
            return View("ManageUserRoles");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GetRoles([Bind(Include = "UserID")]UserRoleVM userRole)
        {
            if (userRole.UserID != null)
            {
                Session["userID"] = userRole.UserID;
                userRole = PopulateVM(userRole.UserID);
                return View("ManageUserRoles", userRole);
            }
            else return RedirectToAction("ManageUserRoles");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteRoleForUser([Bind(Include = "Delete")]UserRoleVM userRole)
        {
            if (Session["userID"] != null)
            {
                string userID = (string)Session["userID"];
                if (userRole.Delete != null)
                {
                    var manager = new UserManager<Member>(
                        new UserStore<Member>(new ForumDb()));
                    if (manager.IsInRole(userID, userRole.Delete))
                    {
                        manager.RemoveFromRole(userID, userRole.Delete);
                    }
                }
                userRole = PopulateVM(userID);
                return View("ManageUserRoles", userRole);
            }
            return View("ManageUserRoles");
        }


        protected UserRoleVM PopulateVM(string userID)
        {
            Member user = context.Users.SingleOrDefault(u => u.Id == userID);
            var manager = new UserManager<Member>(
            new UserStore<Member>(
                new ForumDb()));
            IEnumerable<string> roles = manager.GetRoles(user.Id);
            ViewBag.RolesForThisUser = manager.GetRoles(user.Id);
            UserRoleVM userRole = new UserRoleVM
            {
                UserList = context.Users.OrderBy(u => u.Name).ToList().Select(u =>
                    new SelectListItem { Value = u.Id, Text = u.Name, Selected = (u.Id == user.Id) }).ToList(),
                RoleList = context.Roles.Where(r => !roles.Contains(r.Name)).OrderBy(r => r.Name).ToList().Select(rr =>
                    new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList(),
                Name = user.Name,
                Available = manager.GetRoles(user.Id).Select(x => new SelectListItem() { Text = x.ToString() })
            };
            return userRole;
        }
    }
}

CorvallisOR/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sean White Coding</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Corvallis OR", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Forum", "Index", "Forum")</li>
                    <li>@Html.ActionLink("Map", "Index", "Map")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Welcome, " + Session["user"] + " - Logout", "LogOut", "Auth")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Login", "LogIn", "Auth")</li>
                        <li>@Html.ActionLink("Register", "Register", "Auth")</li>
                    }
                    @if (Session["admin"] != null)
                    {
                        if ((bool)Session["admin"] == true)
                        {
                            <li>@Html.ActionLink("Security", "ManageUserRoles", "Roles")</li>
                        }
                    }
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Sean White Coding</p>
        </footer>
    </div>
</body>
</html>